### ISSUE TITLE
uri encoded %

### ISSUE THREAD

**Issue by pjlammertyn** [geraintluff/uri-templates#16]
is it correct that the uri encode representation of **%** is **%2525** ?
ex:
?filter[body_like]=**%**Ea aut nobis dolorem**%**
uri encoded:
?filter[body_like]=**%2525**Ea%20aut%20nobis%20dolorem**%2525**

**Comment by geraintluff** [comment]
Err... no.  That is not correct.

**Comment by geraintluff** [comment]
Could you post an example template and data, to make sure I get the issue correct?

**Comment by pjlammertyn** [comment]
var uriTemplates = require('uri-templates');

    var uriTemplate = uriTemplates('{/type,ids,relatedField,relationship}{?query*}')
    var url = 'http://localhost:8001/api/messages?filter[body_like]=animi%2525'
    var params = uriTemplate.fromUri(url.split('?').map((part, index) => index > 0 ? decodeURIComponent(part) : part).join('?'))

    console.log(params) //{ query: { 'filter[body_like]': 'animi%' } }

**Comment by geraintluff** [comment]
Why are you percent-decoding the query string before passing it to `.fromUri()`?  The double-encoding error is because you're doing some munging before passing it in.

If you skip your munging, it works as expected:

```javascript
var template = uriTemplates('{/type,ids,relatedField,relationship}{?query*}');
var url = 'http://localhost:8001/api/messages?filter[body_like]=animi%2525';
console.log(template.fromUri(url)); // { query: { 'filter[body_like]': 'animi%25' } }
```

Your munging means that what you're actually passing in to `.fromUri()` is the string: `"http://localhost:8001/api/messages?filter[body_like]=animi%25"` - at which point, the result you're seeing is correct.

**Comment by pjlammertyn** [comment]
I asked, because I thought that it was a bug in [fortune-json-api](https://github.com/fortunejs/fortune-json-api/blob/a091835c11143ad244bb3f8b0c72c2ba5348e0e7/lib/helpers.js#L33-L35), but wasn't sure, even after reading the [rfc6570](http://tools.ietf.org/html/rfc6570).
